name: Test and build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: cargo test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Build binary
      run: docker run --rm -u root -v `pwd`:/home/rust/src ekidd/rust-musl-builder cargo build --release

    - name: save artifacts -- ownserver-auth
      uses: actions/upload-artifact@v2
      with:
        name: ownserver-auth
        path: ./target/x86_64-unknown-linux-musl/release/ownserver-auth